// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iabphuwcmaybqrvivsjz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlhYnBodXdjbWF5YnFydml2c2p6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0MzkxNzAsImV4cCI6MjA1ODAxNTE3MH0.q7156Io4Kv-GW464HJibJrEI1jimbuBZO-B0j_vIeSQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);